### ISSUE TITLE
issues about experiments

### ISSUE THREAD

**Issue by junfeng1212** [junwoopark92/Self-Supervised-Contrastive-Forecsating#2]
Hello! Very interested in your work, the innovative points in it are very interesting to me! Have you tested the multivariate prediction performance of the model on other datasets such as Weather, Electricity, etc.? Can you share their parameters?

**Comment by junwoopark92** [comment]
Thank you for your interest in our research.

To directly answer your question, we measured performance with the same hyperparameters we tested in ETT datasets, but did not observe significant performance improvements worth reporting.

This might simply be due to limited hyperparameter searching, but a more critical issue to consider is whether multiple channels can all have the same long-term correlation (trend or long-term periodicity). We guess It is highly unlikely that they do, and this is a challenge when applying our method to multivariate forecasting. So this is also why we adopted the CI approach in our multivariate experiments concerning ETT.  However, this approach is merely a simple method to extend our method to a multi-channel context. Therefore, we believe considering how to account for long-term correlation in multivariate forecasting is an intriguing topic.

**Comment by junfeng1212** [comment]
> Thank you for your interest in our research.
> 
> To directly answer your question, we measured performance with the same hyperparameters we tested in ETT datasets, but did not observe significant performance improvements worth reporting.
> 
> This might simply be due to limited hyperparameter searching, but a more critical issue to consider is whether multiple channels can all have the same long-term correlation (trend or long-term periodicity). We guess It is highly unlikely that they do, and this is a challenge when applying our method to multivariate forecasting. So this is also why we adopted the CI approach in our multivariate experiments concerning ETT. However, this approach is merely a simple method to extend our method to a multi-channel context. Therefore, we believe considering how to account for long-term correlation in multivariate forecasting is an intriguing topic.

Thank you for your patience in responding ! I couldn't agree with you more . I have seen many papers about  long-trem correlation in multivariate forecasting  from some prestigious conferences, and look forward to your latest findings! 
Thanks again！
